<a href="https://colab.research.google.com/github/Kotte-Shivani/NASSCOM/blob/main/WEEK%202/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

s1_1 = pd.Series([10, 20, 30, 40, 50])

np_array1_2 = np.random.randint(1, 101, size=(3, 4))

df1_3 = pd.DataFrame(np_array1_2, columns=["A", "B", "C", "D"])

print(s1_1)
print(np_array1_2)
print(df1_3)

print("\n--- Task 2: Synthetic Data Generation for Practice ---")

np.random.seed(42)

df_sales = pd.DataFrame({
    "Date": pd.date_range("2023-01-01", periods=100),
    "Region": np.random.choice(["East", "West", "North", "South"], 100),
    "Product": np.random.choice(["Laptop", "Mouse", "Keyboard", "Monitor"], 100),
    "Sales": np.random.randint(100, 1001, 100).astype(float),
    "Quantity": np.random.randint(1, 11, 100).astype(float)
})

sales_nan = np.random.choice(df_sales.index, 5, replace=False)
quantity_nan = np.random.choice(df_sales.index, 3, replace=False)

df_sales.loc[sales_nan, "Sales"] = np.nan
df_sales.loc[quantity_nan, "Quantity"] = np.nan

print(df_sales.head())

print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

df3_1 = df_sales[["Region", "Sales"]]

df3_2 = df_sales[df_sales["Product"] == "Laptop"]

df3_3 = df_sales[(df_sales["Region"] == "East") & (df_sales["Sales"] > 500)]

val3_4 = df_sales.loc[df_sales[df_sales["Product"] == "Monitor"].index[0], "Sales"]

print(df3_1.head())
print(df3_2.head())
print(df3_3.head())
print(val3_4)

print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

missing_counts4_1 = df_sales.isna().sum()

df4_2_filled = df_sales.copy()
df4_2_filled["Sales"] = df4_2_filled["Sales"].fillna(df4_2_filled["Sales"].mean())

df4_3_dropped = df_sales.dropna()

print(missing_counts4_1)
print(df4_2_filled.head())
print(df4_3_dropped.head())

print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

df_sales["Total_Revenue"] = df_sales["Sales"] * df_sales["Quantity"]

df5_2_sorted = df_sales.sort_values(by=["Date", "Sales"], ascending=[True, False])

df5_3_grouped_region = df_sales.groupby("Region")[["Sales", "Quantity"]].sum()

df5_4_grouped_product = df_sales.groupby("Product")["Sales"].mean()

print(df_sales.head())
print(df5_2_sorted.head())
print(df5_3_grouped_region)
print(df5_4_grouped_product)


--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
0    10
1    20
2    30
3    40
4    50
dtype: int64
[[ 52  93  15  72]
 [ 61  21  83  87]
 [ 75  75  88 100]]
    A   B   C    D
0  52  93  15   72
1  61  21  83   87
2  75  75  88  100

--- Task 2: Synthetic Data Generation for Practice ---
        Date Region   Product  Sales  Quantity
0 2023-01-01  North  Keyboard  674.0       7.0
1 2023-01-02  South     Mouse  963.0       4.0
2 2023-01-03   East     Mouse    NaN       7.0
3 2023-01-04  North   Monitor  340.0       8.0
4 2023-01-05  North     Mouse  663.0       1.0

--- Task 3: Indexing and Slicing in DataFrames ---
  Region  Sales
0  North  674.0
1  South  963.0
2   East    NaN
3  North  340.0
4  North  663.0
         Date Region Product  Sales  Quantity
16 2023-01-17  South  Laptop  624.0       4.0
19 2023-01-20  North  Laptop